server:
  port: 8080
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3307/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
      username: root
      password: wangzhe123
mybatis:
  mapper-locations:
#    - 要点说明,classpath:不能有空格
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml